name: movienv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - streamlit=1.37.0
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - plotly=5.23.0
  - seaborn=0.13.2
  - statsmodels
  - pip